[custom]
;不要随意改变关键字，否则会导致出错
;skull规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持

surge_ruleset=🇨🇳 国内网站,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/LocalAreaNetwork.list
surge_ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
surge_ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
surge_ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
surge_ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
surge_ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
surge_ruleset=🎮 游戏平台,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/YouXiPingTai.list
surge_ruleset=🧩 微软服务,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/WeiRuanFuWu.list
surge_ruleset=🍎 苹果服务,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/PingGuoFuWu.list
surge_ruleset=📲 聊天软件,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/LiaoTianRuanJian.list
surge_ruleset=🌍 国外媒体,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/GuoWaiMeiTi_2.list
surge_ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/BaHaMuTe.list
surge_ruleset=▶ YouTube,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/YOUTUBE.list
surge_ruleset=🎥 NETFLIX,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/NETFLIX.list
surge_ruleset=🎵 TikTok,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/TikTok.list
surge_ruleset=🎬 Prime,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/PrimeVideo.list
surge_ruleset=👪 DisneyPlus,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/DisneyPlus.list
surge_ruleset=🎬 HBO,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/HBO.list
surge_ruleset=🎬 Spotify,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/Spotify.list
surge_ruleset=⛩ 日韩媒体,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/RiHanMeiTi.list
surge_ruleset=🌏 港台媒体,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/GangTaiMeiTI_2.list
surge_ruleset=📺 哔哩哔哩&爱奇艺,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/BilibiliHMT.list
surge_ruleset=📺 哔哩哔哩&爱奇艺,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/IqiyiHMT.list
surge_ruleset=🇧🇹 BT&PT,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/PrivateTracker.list
surge_ruleset=🇺🇳 国外网站,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/GuoWaiWangZhan.list
surge_ruleset=🇺🇳 国外网站,https://raw.githubusercontent.com/skullssr/merlinclash_clash_related/master/Rules/User/GuowaiCust.list
surge_ruleset=🇨🇳 国内网站,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ZHANG/GuoNeiWangZhan.list
surge_ruleset=🇨🇳 国内网站,https://raw.githubusercontent.com/skullssr/merlinclash_clash_related/master/Rules/User/GuowaiDirect.list
surge_ruleset=🇨🇳 国内网站,[]GEOIP,CN
surge_ruleset=📡 Emby,https://raw.githubusercontent.com/skullssr/merlinclash_clash_related/master/Rules/User/StreamMedia.list
surge_ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300
custom_proxy_group=▶ YouTube`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 NETFLIX`select`[]🎥 奈飞节点`[]🚀 节点选择`.*`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩&爱奇艺`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🌍 其他地区`[]🚀 手动切换
custom_proxy_group=🎬 Prime`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=👪 DisneyPlus`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎬 Spotify`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎬 HBO`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=⛩ 日韩媒体`select`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 港台媒体`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换
custom_proxy_group=🧩 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换
custom_proxy_group=📲 聊天软件`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📡 Emby`select`[]DIRECT`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换
custom_proxy_group=🇧🇹 BT&PT`select`[]DIRECT`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换
custom_proxy_group=🇺🇳 国外网站`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🇨🇳 国内网站`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🌍 其他地区`[]🚀 手动切换
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT
custom_proxy_group=🇭🇰 香港节点`url-test`(港((?!.*IPLC)+(?!.*IEPL))|HK((?!.*IPLC)+(?!.*IEPL))|Hong Kong((?!.*IPLC)+(?!.*IEPL)))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇯🇵 日本节点`url-test`(日((?!.*IPLC)+(?!.*IEPL))|东京((?!.*IPLC)+(?!.*IEPL))|大阪((?!.*IPLC)+(?!.*IEPL))|埼玉((?!.*IPLC)+(?!.*IEPL))|JP((?!.*IPLC)+(?!.*IEPL))|Japan((?!.*IPLC)+(?!.*IEPL)))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇺🇲 美国节点`url-test`(美((?!.*IPLC)+(?!.*IEPL))|波特兰((?!.*IPLC)+(?!.*IEPL))|达拉斯((?!.*IPLC)+(?!.*IEPL))|俄勒冈((?!.*IPLC)+(?!.*IEPL))|凤凰城((?!.*IPLC)+(?!.*IEPL))|费利蒙((?!.*IPLC)+(?!.*IEPL))|硅谷((?!.*IPLC)+(?!.*IEPL))|拉斯维加斯((?!.*IPLC)+(?!.*IEPL))|洛杉矶((?!.*IPLC)+(?!.*IEPL))|圣何塞((?!.*IPLC)+(?!.*IEPL))|圣克拉拉((?!.*IPLC)+(?!.*IEPL))|西雅图((?!.*IPLC)+(?!.*IEPL))|芝加哥((?!.*IPLC)+(?!.*IEPL))|US((?!.*IPLC)+(?!.*IEPL))|United States((?!.*IPLC)+(?!.*IEPL)))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇨🇳 台湾节点`url-test`(台((?!.*IPLC)+(?!.*IEPL))|新北((?!.*IPLC)+(?!.*IEPL))|彰化((?!.*IPLC)+(?!.*IEPL))|TW((?!.*IPLC)+(?!.*IEPL))|Taiwan((?!.*IPLC)+(?!.*IEPL)))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇸🇬 狮城节点`url-test`(坡((?!.*IPLC)+(?!.*IEPL))|狮城((?!.*IPLC)+(?!.*IEPL))|SG((?!.*IPLC)+(?!.*IEPL))|Singapore((?!.*IPLC)+(?!.*IEPL)))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR((?!.*IPLC)+(?!.*IEPL))|Korea((?!.*IPLC)+(?!.*IEPL))|KOR((?!.*IPLC)+(?!.*IEPL))|首尔((?!.*IPLC)+(?!.*IEPL))|韩((?!.*IPLC)+(?!.*IEPL))|韓((?!.*IPLC)+(?!.*IEPL)))`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🌍 其他地区`select`(俄|印|德|英|土|阿|拿|菲|澳)
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)`[]🚀 手动切换


enable_rule_generator=true
overwrite_original_rules=true

